project:
  type: website
  output-dir: _site


website:
  title: "Tashi Tshering Tamang"
  navbar:
    left:
      - text: "ABOUT"
        href: "#about"
      - text: "EDUCATION"
        href: "#education"
      - text: "EXPERIENCE"
        href: "#experience"
      - text: "SKILLS"
        href: "#skills"
      - text: "LEADERSHIP"
        href: "#leadership"
      - text: "CONTACT"
        href: "#contact"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
